apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-regler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 5
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  resources:
    requests:
      cpu: 20m
      memory: 450Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pale-2
    outbound:
      rules:
        - application: syfohelsenettproxy
        - application: btsys-api
          namespace: team-rocket
          cluster: prod-gcp
        - application: tsm-pdl-cache
          namespace: tsm
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  env:
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.btsys-api/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
