apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-regler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 50m
      memory: 250Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: pale-2
          namespace: teamsykmelding
          cluster: dev-gcp
    outbound:
      rules:
        - application: syfohelsenettproxy
      external:
        - host: syfohelsenettproxy.dev-fss-pub.nais.io
        - host: smgcp-proxy.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  env:
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: LEGE_SUSPENSJON_PROXY_ENDPOINT_URL
      value: https://smgcp-proxy.dev-fss-pub.nais.io
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://dev-fss.teamsykmelding.smgcp-proxy/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
