apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-regler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 5
    cpuThresholdPercentage: 80
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: pale-2
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: syfohelsenettproxy
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: btsys.prod-fss-pub.nais.io
  env:
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: LEGE_SUSPENSJON_PROXY_ENDPOINT_URL
      value: https://btsys.prod-fss-pub.nais.io
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://prod-fss.team-rocket.btsys/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
